### ISSUE TITLE
Infinite pending channel (Zap)

### ISSUE THREAD

**Issue by imacfan** [apotdevin/thunderhub#121]
I opened a channel with Zap. It is showing in pending state for a week now. 

Anyway to fix this? How do I force close and get my funds back?

![image](https://user-images.githubusercontent.com/54225190/90002576-73994200-dcb0-11ea-9faf-dc93652586c7.jpeg)

**Comment by apotdevin** [comment]
mmm not sure... would be best if you go to the lightning labs slack channel since this is more an LND issue than a ThunderHub one

LL slack: https://join.slack.com/t/lightningcommunity/shared_invite/enQtOTE3Mjc0MDQ0MTY3LWQ1NGNjNzg2YjFiNWU0NWIzZjBjYzQ0OGQ2Mzg1YmE2NjU4ODBhM2I2YTU5MTAzYzVmYzVlMTQzNGNjNGJkNGU

**Comment by bloodir** [comment]
It has happened to me also due to apparently paying low fee. You can see the pending channel with _lncli pendingchannels_ and try to rebroadcast with the _bitcoin-cli sendrawtransaction_ that may give you the error with fee not being sufficient. You can then do _bitcoin-cli prioritisetransaction "txid" 0.0 [fee]_ to bump up the transaction fee/priority and the rebroadcast it with  _bitcoin-cli sendrawtransaction_ It did help to me and the transaction broadcasted and channel opened.

**Comment by imacfan** [comment]
Thanks. Let me try that

**Comment by imacfan** [comment]
> It has happened to me also due to apparently paying low fee. You can see the pending channel with _lncli pendingchannels_ and try to rebroadcast with the _bitcoin-cli sendrawtransaction_ that may give you the error with fee not being sufficient. You can then do _bitcoin-cli prioritisetransaction "txid" 0.0 [fee]_ to bump up the transaction fee/priority and the rebroadcast it with _bitcoin-cli sendrawtransaction_ It did help to me and the transaction broadcasted and channel opened.

I ran prioritisetransaction - returned "true", How to get the myHex or signedHex..?

**Comment by bloodir** [comment]
Sorry forgot about this. Use _lncli listchaintxn_ and find the transaction you need to rebroadcast. raw_tx_hex: is what you need.

**Comment by imacfan** [comment]
> lncli listchaintxn

How do I know Tx hash is pending? It is showing "num_confirmations": 799, but "total_fees": "0",.. is it pending with so many confirmations?

**Comment by imacfan** [comment]
> Sorry forgot about this. Use _lncli listchaintxn_ and find the transaction you need to rebroadcast. raw_tx_hex: is what you need. Tx hash should match to your pending transaction.

Run - sendrawtransaction after bumping the fee. Got this error: 
"error code: -27"
"error message:"
"Transaction already in block chain"

Does it mean this transaction is already confirmed and fee is not the issue?

**Comment by imacfan** [comment]
Solved using Bumpfee https://github.com/lightningnetwork/lnd/issues/4530
