### ISSUE TITLE
How do I connect to my node through a LNDConnect URL?

### ISSUE THREAD

**Issue by GiovanniBordiga** [apotdevin/thunderhub#141]
**Describe the problem/bug**
The README reports the possibility to connect to my lnd node through a LNDConnect URL, but I can't find the way to make it work. Sorry to bother but I could not find any documentation on how to do this.
I suppose there is a dedicated way to configure the YAML file defining the accounts.

**Expected behavior**
There should be a way to connect to my node via a lndconnect URL, but it is probably not documented.

Thanks a lot in advance, and keep up the great work! :sunglasses: :muscle:

**Comment by apotdevin** [comment]
Ah yes, this was removed some versions ago since it involved storing sensitive data in the browsers storage. Now to connect you must create an accounts file like it's shown [here](https://github.com/apotdevin/thunderhub#server-accounts) and let thunderhub know where this file is.

I've updated the README to correct this! and thanks!

**Comment by GiovanniBordiga** [comment]
@apotdevin thanks!
