### ISSUE TITLE
Please revert the last breaking change

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#190]
**Is your feature request related to a problem? Please describe.**
The latest release log says:

> `BASE_PATH` is no longer a runtime environment variable but a build time environment variable

This greatly affects quality of my Debian packaging. Currently being able to set the variable run-time is a feature exposed to the users. Rebuilding whole ThunderHub is not acceptable as its executables can be stored in read-only memory and is very slow. Removing this feature is possible but it keeps yet another big problem.

Currently I allow installation of mainnet and regtest versions together. Regtest uses a different path to not clash with mainnet. To avoid duplication, the same executable is used for regtest and mainnet.

Having it baked-in would mean installing ThunderHub twice. This is a waste of space and worse, the installation already takes a very long time. Further, building and testing of ThunderHub takes a very long time too. This change would cause it to double. (and triple when I decide to provide testnet and quadruple when I also provide signet).

I guess the intent of the change was to optimize the speed. Firstly I don't think speed was so bad it'd justify this kind of breakage. Secondly this problem can be better solved by using a cache.

**Describe the solution you'd like**
Revert the last change and optimize the speed using a cache if needed.

**Describe alternatives you've considered**
The alternatives are terrible:

* Keep old ThunderHub risking vulnerabilities
* Maintain a fork of ThunderHub, slowing down development
* Let the costs of ThunderHub packaging double/triple/quadruple
* Invent some horrible hack to work this around
* Stop supporting ThunerHub

**Comment by apotdevin** [comment]
Hey! Oh man, sorry I messed this up for you.

The reason for the change is actually rooted in a breaking change coming directly from the [lib](https://nextjs.org/docs/api-reference/next.config.js/basepath) on which ThunderHub is based. I had managed to avoid this breaking change by manually adding the basePath to links and assets but it was not working as expected and was adding 'dirty' code to the codebase. It was also breaking the single page application behaviour and causing a reload of data on any view change instead of using a cache.

I had also tried to avoid it completely because of the current integration with BTCPay that requieres a base path but ultimately this complication was outweighed by the broken functionality that was fixed with doing the change.

To get some context how do your users currently reach the different instances?

Would it be an option for you to run each instance on different ports? What I'm thinking is that maybe you can build a single instance with a specific basepath and then run however many servers you want on different ports (which can be set at runtime)

**Comment by Kixunil** [comment]
The users are allowed to choose any URL they wish, however most (all?) go with the default `/thunderhub` for mainnet and `/thunderhub-rt` for regtest. The instances are already completely isolated (port, user, ...) and only share the domain name.

I'm not sure I understand the question about the ports though, since running it on the same port should be impossible. Maybe you mean that users would have to access it with URL having `:123` inside? Because I suspect that would break certificates and probably greatly complicate some other things as the whole thing is behind nginx.

Any chance of the feature being added to the library or using something else?

Thanks for all your effort keeping it working so far!

**Comment by apotdevin** [comment]
Ah it's behind nginx, yeah that will probably not work then.

I've been asking in the nextjs github repo but there doesn't seem to be a lot of demand to have this as a runtime env. Here are two discussions i've started that unfortunately didn't get any traction:

https://github.com/vercel/next.js/discussions/20215
https://github.com/vercel/next.js/discussions/16059

Is it an option to have the config for all nodes (mainnet, testnet, regtest, ...) in the same thunderhub config file? or do they need to be completely separate instances?

**Comment by Kixunil** [comment]
Isolation is preferred for security but using a single instance for all configured versions is an acceptable compromise given the situation. (The security increase isn't huge anyway considering that the codebase is the same.) It needs to work with SSO. I guess some dropdown to select the node would be nice. RTL works similarly - allows setting up arbitrary set of nodes and has a fixed `/rtl` base path.

`/thunderhub` being baked-in is not great so if anything changes in the libraries to support dynamic paths cleanly in the future I'd highly appreciate if we could get the feature back.

**Comment by apotdevin** [comment]
Yeah for sure I'll keep the baked base path in mind 👍 

SSO currently only works with a single account so that would be something that needs to be added. Would you mind opening a new ticket for the multiple SSO setup? Would be nice to know what you are expecting. Does each account have a different cookie/cookie path? How does the user choose which env he logs in to?

**Comment by Kixunil** [comment]
OK, I opened #202

**Comment by apotdevin** [comment]
Perfect, thanks! I would then close this ticket :)
