### ISSUE TITLE
Transaction Not Broadcast

### ISSUE THREAD

**Issue by definitivequestion** [apotdevin/thunderhub#246]
**Describe the problem/bug**
I tried opening a new channel from the ThunderHub interface, but it has never appeared in the mempool. I can however see it in the mempool of my local node.

**Your environment**
* Version of ThunderHub: 0.12.12
* Deployment method: myNode Installer
* Other relevant environment details: Raspberry Pi 4 B 8GB, 64-bit Debian Bullseye, Bitcoin Core v21

**To Reproduce**
No idea how to reproduce, but perhaps it has something to do with high mempool congestion. Mempool.space has 450 / 300 MB mempool size with over 200 MB of pending transactions. At the time I tried opening the channel, the fees went from around 60 sats/vByte to 10 sats/vByte because a lot of mining capacity came online. The fees have spiked and fallen repeatedly during this time. However, I paid 14 sats/vByte which should be more than the purge limit and was considered a high priority transaction at the time.

**Expected behavior**
The channel opening transaction gets relayed to the Bitcoin network.

**Actual behavior**
Transaction is not relayed to Bitcoin network.

**Comment by apotdevin** [comment]
Hi! This isn't related to Thunderhub so will close this issue.

Depending on when you opened the channel it might take some time to propagate to other nodes. Seems like a reasonable fee, I think it's a matter of waiting (Unless you opened the channel more than 2 weeks ago since LND doesnt keep track of transaction after this time).
