### ISSUE TITLE
--insecure-http-parser is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by darrenahunter** [apotdevin/thunderhub#30]
fresh clone and install of thunderhub
running on node v12
yarn start fails with --insecure-http-parser is not allowed in NODE_OPTIONS

log from terminal follows

darrenhunter@192-168-1-9 thunderhub % yarn start
yarn run v1.22.4
$ cross-env NODE_OPTIONS='--insecure-http-parser' next start
/usr/local/bin/node: --insecure-http-parser is not allowed in NODE_OPTIONS
error Command failed with exit code 9.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
darrenhunter@192-168-1-9 thunderhub % code .
darrenhunter@192-168-1-9 thunderhub % node --version
v12.13.1

removing the NODE_OPTIONS from the start script works and next starts up

**Comment by apotdevin** [comment]
Hi, passing `insecure-http-header` is only available from node `v12.15.0`. (https://github.com/nodejs/node/issues/27711#issuecomment-584621376)

Currently the only reason for passing it is because of the HodlHodl integration. There API seems to be passing invalid HTTP headers thus the need to add the param. Apart from the HodlHodl integration, everything else should work as expected if you remove this options from the start scripts.

Seeing as it's only for the HodlHodl integration will see if it makes sense to remove this from the start scripts and have another script to start with it.
