### ISSUE TITLE
Replace pubkeys with Node names for legibility in screens with "hops"

### ISSUE THREAD

**Issue by Swissnode** [apotdevin/thunderhub#58]
**Is your feature request related to a problem? Please describe.**
Pubkeys don't mean much but node names do

**Describe the solution you'd like**
The following:

![image](https://user-images.githubusercontent.com/54310929/83738345-7cd4b580-a654-11ea-932a-865b31437c6c.png)

should be replaced with the name of the node that the hop went through. Additionally you could put a "copy" icon to the right in case the user wants to copy the pubkey, and you could also make the name hyperlinked to the 1ML page of the node...

**Describe alternatives you've considered**
N/A

**Provide examples**
N/A

**Comment by apotdevin** [comment]
I like the idea, need to check how viable it is because a new request has to be done for each pubkey to get the full node info, but would definitely be nicer 👍 

Also the copy icon is something I've been meaning to add but havent had the time, will include (hopefully) in the next release

Thanks for the requests!

**Comment by accumulator** [comment]
The hop names are correct, but the pubkey for each hop is incorrect. They are all the pubkey of the user's node

**Comment by apotdevin** [comment]
Thanks for finding this! It's fixed in v.0.7.10
